# docker run --name myredis -p 6379:6379 -d redis
#   docker run -d --name myelasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.8.1
#   docker run -d --name mykibana --link myelasticsearch:elasticsearch  -p 5601:5601 kibana:7.8.1
#   docker run -d --name mymongo -p 28017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=admin123 mongo:latest
#   docker run -d --name mymysql -e MYSQL_ROOT_PASSWORD=admin123 -e MYSQL_USER=tapos -e MYSQL_PASSWORD=admin123  percona:8.0
#  docker run -d --name myadmin  --link mymysql:db -p 8080:80 -e MYSQL_ROOT_PASSWORD=admin123 phpmyadmin/phpmyadmin
#   docker run -d --name myrabbit -p 15672:15672 -p 5672:5672  -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=admin123 rabbitmq:3-management

version: "3.8"
services:
  myredis:
    image: redis
    container_name: myredis
    ports:
      - 6379:6379
    restart: always
    networks:
      - mytestproject

  myelastic:
    image: elasticsearch:7.8.1
    container_name: myelastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - mytestproject

  mykibana:
    image: kibana:7.8.1
    container_name: mykibana
    ports:
      - 5601:5601
    links:
      - myelastic:elasticsearch
    networks:
      - mytestproject

  mymongo:
    image: mongo:latest
    container_name: mymongo
    ports:
      - 28017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - mytestproject

  mymysql:
    image: percona:8.0
    container_name: mymysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=tapos
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE= default_schema
    networks:
      - mytestproject

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=tapos
      - MYSQL_PASSWORD=admin123
    links:
      -  mymysql:db 
      
    networks:
      - mytestproject
  myrabbit:
    image: rabbitmq:3-management
    container_name:  myrabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - mytestproject

networks:
  mytestproject:
    driver: bridge
      